### ISSUE TITLE
Wrong package for ChannelAwareMessageListener in SpringAMQPMessageSource (boot 2.1)

### ISSUE THREAD

**Issue by JonatanE** [AxonFramework/extension-amqp#1]
ChannelAwareMessageListener has been moved to org.springframework.amqp.rabbit.listener.api in Spring boot 2.1.

**Comment by smcvb** [comment]
I noted this is based on the `spring-rabbit` version, not the `spring-boot` version (which was already on 2.1.2 for this repository). Regardless, I'll update the `spring-rabbit` version to the latest and adjust the import statements.

**Comment by smcvb** [comment]
Closing this issue as it has been resolved in commit af4da86.
